openapi: 3.0.1
info:
  title: Swagger Petstore
  description: 'This is a sample server Petstore server.  You can find out more about     Swagger
    at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For
    this sample, you can use the api key `special-key` to test the authorization     filters.'
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://localhost:3001
tags:
- name: task
  description: Operation about tasks
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
paths:
  /login:
    post:
      tags:
      - user
      summary: User log into the server
      requestBody:
        description: User object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_pass'
        required: true
      responses:
        "401":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-swagger-router-controller: User
  /tasks:
    get:
      tags:
      - task
      operationId: tasksGET
      responses:
        "200":
          description: Tutto giusto tutto legistimo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/task'
                x-content-type: application/json
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/server_error'
      x-swagger-router-controller: Task
    post:
      tags:
      - task
      summary: add new task
      operationId: tasksPOST
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/new_task'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "401":
          description: authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth_error'
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/server_error'
      x-codegen-request-body-name: body
      x-swagger-router-controller: Task
  /tasks/{id}:
    get:
      tags:
      - task
      summary: sas
      description: sad
      operationId: tasksIdGET
      parameters:
      - name: id
        in: path
        description: as
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/task'
        "401":
          description: authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth_error'
        "404":
          description: NOT Found
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/server_error'
      x-swagger-router-controller: Task
    put:
      tags:
      - task
      operationId: tasksIdPUT
      parameters:
      - name: id
        in: path
        description: asd
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        description: update task obj
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/task'
        required: true
      responses:
        "200":
          description: OK
          content: {}
        "400":
          description: Bad request
        "401":
          description: authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth_error'
        "404":
          description: Not found
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/server_error'
      x-codegen-request-body-name: body
      x-swagger-router-controller: Task
    delete:
      tags:
      - task
      summary: asd
      description: as
      operationId: tasksIdDELETE
      parameters:
      - name: id
        in: path
        description: asd
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content: {}
        "401":
          description: authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth_error'
        "404":
          description: Not found
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/server_error'
      x-swagger-router-controller: Task
  /tasks/user:
    get:
      tags:
      - task
      operationId: tasksUserGET
      responses:
        "200":
          description: Tutto giusto tutto legistimo
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/task'
                x-content-type: '*/*'
        "401":
          description: authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth_error'
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/server_error'
      x-swagger-router-controller: Task
  /logout:
    post:
      tags:
      - user
      operationId: logoutPOST
      responses:
        "200":
          description: Clear cookie
      x-swagger-router-controller: User
components:
  schemas:
    user:
      required:
      - email
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
          format: email
        password:
          minLength: 6
          type: string
    task:
      required:
      - description
      - id
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
        important:
          type: boolean
          default: false
        private:
          type: boolean
          default: true
        projects:
          type: array
          items:
            $ref: '#/components/schemas/project_name'
        date:
          type: string
          format: date
        completed:
          type: boolean
          default: false
        assignedTo:
          type: array
          items:
            type: integer
      example:
        important: false
        date: 2000-01-23
        private: true
        projects:
        - Personal
        - Personal
        description: description
        id: 0
        completed: false
        assignedTo:
        - 6
        - 6
    project_name:
      type: string
      enum:
      - Personal
      - WA1_Project
      - WA2_Project
      - DSP_Project
    new_task:
      required:
      - description
      - id
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
        important:
          type: boolean
          default: false
        private:
          type: boolean
          default: true
        projects:
          type: array
          items:
            $ref: '#/components/schemas/project_name'
        date:
          type: string
          format: date
        completed:
          type: boolean
          default: false
        assignedTo:
          type: array
          items:
            type: integer
    user_pass:
      required:
      - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    server_error:
      type: object
      properties:
        param:
          type: string
        msg:
          type: string
    auth_error:
      type: object
      properties:
        param:
          type: string
        msg:
          type: string
    inline_response_200:
      type: object
      properties:
        id:
          type: string
      example:
        id: id
